export const GAME_CONFIG = {
  GAME_DURATION: 30,
  MOLE_MIN_DURATION: 500,
  MOLE_MAX_DURATION: 3000,
  MAX_ACTIVE_MOLES: 6, // Increased from 4 to 6
  MOLE_SCORE: 2,
  BOMB_SCORE: -1,
  BOMB_PROBABILITY: 0.2,
  HOLE_LAYOUT: [4, 3, 4],
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
};